[package]
name = "nn"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
nalgebra = { version = "0.33", features = ["serde-serialize"] }
rand = "0.9"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
csv = "1.3"
